import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { useQuery } from "@tanstack/react-query";

export default function Home() {
  const fetchUsers = async () => {
    const res = await fetch("https://jsonplaceholder.typicoe.com/users");
    return res.json();
  };
  const { data, status } = useQuery({
    queryKey: ["users"],
    queryFn: fetchUsers,
    throwOnError: true,
  });

  console.log(status);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>

      {status === "error" && <div>Error fetching data</div>}
      {status === "pending" && <div>Fetching data...</div>}
      {status === "success" && (
        <div>
          {data.map((user) => (
            <p key={user.id}>{user.name}</p>
          ))}
        </div>
      )}
    </>
  );
}
